// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'light-default', 'light-ocean', 'light-forest', 'light-sunset', 'light-lavender', 'dark-default', 'dark-ocean', 'dark-forest', 'dark-sunset', 'dark-lavender']
    }
}

export {}
